# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-04 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190204_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='music',
        ),
    ]
